### PR TITLE
v3.2.0-rc1-34-g878edeb6ff19: stm32 results

### PR DESCRIPTION
**Pull request by erwango**
Non reg result analysis on last run:

Failed tests:
   (verdicts: T/p: Passed, F/f: Failed, t:timeout)
   samples/sensor/stm32_temp_sensor/sample.sensor.stm32_temp_sensor, b_u585i_iot02a
   samples/sensor/stm32_temp_sensor/sample.sensor.stm32_temp_sensor, disco_l475_iot1
   samples/sensor/stm32_temp_sensor/sample.sensor.stm32_temp_sensor, nucleo_l073rz
   samples/sensor/stm32_temp_sensor/sample.sensor.stm32_temp_sensor, nucleo_l152re
   samples/sensor/stm32_temp_sensor/sample.sensor.stm32_temp_sensor, nucleo_wl55jc
   samples/sensor/stm32_temp_sensor/sample.sensor.stm32_temp_sensor, stm32f3_disco
   tests/arch/arm/arm_interrupt/arch.interrupt.extra_exception_info, stm32f3_disco
   tests/arch/arm/arm_interrupt/arch.interrupt.no_optimizations, stm32f3_disco
   tests/arch/arm/arm_thread_swap/arch.arm.swap.common, nucleo_g071rb
   tests/arch/arm/arm_thread_swap/arch.arm.swap.common, nucleo_l073rz
   tests/drivers/adc/adc_api/drivers.adc, nucleo_wb55rg
   tests/drivers/adc/adc_api/drivers.adc, nucleo_wl55jc
   tests/drivers/adc/adc_api/drivers.adc, stm32l562e_dk
   tests/drivers/can/shell/drivers.can.shell, nucleo_f207zg
   tests/drivers/flash/drivers.flash.default, nucleo_l152re
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, disco_l475_iot1
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_f103rb
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_f207zg
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_f429zi
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_f746zg
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_g071rb
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_g474re
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_l152re
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_wb55rg
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, nucleo_wl55jc
   tests/drivers/gpio/gpio_basic_api/drivers.gpio.2pin, stm32f3_disco
   tests/drivers/uart/uart_async_api/drivers.uart.async_api, nucleo_f429zi
   tests/kernel/mem_protect/mem_protect/kernel.memory_protection, nucleo_f746zg
   tests/kernel/mem_protect/userspace/kernel.memory_protection.userspace, nucleo_g071rb
   tests/kernel/mem_protect/userspace/kernel.memory_protection.userspace, nucleo_l073rz
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, b_u585i_iot02a
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, disco_l475_iot1
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, nucleo_g071rb
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, nucleo_l073rz
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, nucleo_wb55rg
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, nucleo_wl55jc
   tests/kernel/tickless/tickless_concept/kernel.tickless.concept, stm32l562e_dk
   tests/kernel/timer/timer_api/kernel.timer.tickless, b_u585i_iot02a
   tests/lib/cmsis_dsp/basicmath/libraries.cmsis_dsp.basicmath, nucleo_wb55rg
   tests/lib/cmsis_dsp/basicmath/libraries.cmsis_dsp.basicmath.fpu, nucleo_g474re
   tests/lib/cmsis_dsp/complexmath/libraries.cmsis_dsp.complexmath.fpu, nucleo_f746zg (instable: ppppepppeppeeppep)
   tests/lib/cmsis_dsp/statistics/libraries.cmsis_dsp.statistics.fpu, nucleo_h743zi (instable: ppppppppeppeeeppe)
   tests/lib/cmsis_dsp/statistics/libraries.cmsis_dsp.statistics.fpu, stm32l562e_dk (instable: peppppppeppeepppp)
   tests/lib/cmsis_dsp/support/libraries.cmsis_dsp.support.fpu, nucleo_f746zg (instable: ppepppepeppeeppep)
   tests/lib/cmsis_dsp/support/libraries.cmsis_dsp.support.fpu, nucleo_g474re (instable: ppppepppeppeepppp)
   tests/lib/cmsis_dsp/transform/libraries.cmsis_dsp.transform.cf64, disco_l475_iot1
   tests/lib/cmsis_dsp/transform/libraries.cmsis_dsp.transform.cf64.fpu, disco_l475_iot1
   tests/lib/cmsis_dsp/transform/libraries.cmsis_dsp.transform.rf32, nucleo_l152re
   tests/subsys/canbus/isotp/implementation/canbus.isotp.implementation, nucleo_g474re
   tests/subsys/fs/fs_api/filesystem.api, nucleo_l152re (instable: ppppppepepeeepppp)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, nucleo_f746zg (instable: peppepepepeeeeepp)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, nucleo_l073rz (instable: pppeppppeppeepppe)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, nucleo_l152re (instable: peppppppepeeeeepp)
   tests/subsys/shell/shell/shell.core, nucleo_l152re (instable: pppppppeepeeepppe)

Total: 54 test(s) failed out of 5782 tests run
       5728 test(s) passed
       0 regression(s) on stable test
Recently skipped or filtered: 1022

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by hakehuang** [comment]
@erwango is this platform result correct?
results/v3.2.0-rc1-34-g878edeb6ff19/disco_l475_iot1.xml has too many failures (>500. It requires manual verification.)

**Comment by erwango** [comment]
> @erwango is this platform result correct? results/v3.2.0-rc1-34-g878edeb6ff19/disco_l475_iot1.xml has too many failures (>500. It requires manual verification.)

Weird... I'll have a check.

**Comment by erwango** [comment]
@hakehuang It seems this is coming from `tests/lib/cmsis_dsp/transform/libraries.cmsis_dsp.transform.*` tests which generates multiple failures for one test (eg: 660 for ``libraries.cmsis_dsp.transform.cf64`).
Is that blocking ?

**Comment by hakehuang** [comment]
> @hakehuang It seems this is coming from `tests/lib/cmsis_dsp/transform/libraries.cmsis_dsp.transform.*` tests which generates multiple failures for one test (eg: 660 for ``libraries.cmsis_dsp.transform.cf64`).
> Is that blocking ?

Do you report issue? if so, then this is not a blocking

**Comment by erwango** [comment]
> Do you report issue? if so, then this is not a blocking. @erwango

@hakehuang No, I don't report an issue on this, if the test is implemented this way there might be reasons. Indeed I don't think this should be blocking for a test report.

**Pull request merged**
