### PR TITLE
zephyr-v2.3.0-397-g540ed95786: stm32 results

### PR DESCRIPTION
**Pull request by erwango**
Non reg result analysis on last run:
   (verdicts: T/p: Passed, F/f: Failed, t:timeout)
   samples/subsys/nvs/sample.nvs.basic, stm32f3_disco 
                (instable: ptttttttttppttttt)
   tests/kernel/mem_protect/userspace/kernel.memory_protection.userspace, nucleo_f429zi 
                (instable: pppppptptpppppptp)
   tests/kernel/mem_protect/userspace/kernel.memory_protection.userspace, nucleo_f746zg 
                (instable: pppptppppppppptpp)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, nucleo_f429zi
                (instable: pppppptpppppptppppp)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, stm32f3_disco
                (instable: ppppppppptptpppptpp)

Total: 21 test(s) failed out of 1522 tests run
       0 regression(s) on stable test

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Comment by nashif** [comment]
@erwango  you should not be upload sanitycheck*.xml  files...

**Comment by erwango** [comment]
> @erwango you should not be upload sanitycheck*.xml files...

@nashif Yeah I saw that. Not sure what happens here as I normally clean them up.
I'll try to fix get this fixed today/tomorrow (fix script, update current PR, and clean previous results if needed)

**Comment by erwango** [comment]
@nashif Not sure what is the problem here:
```
Run curl https://testing.zephyrproject.org/daily_tests/versions.json -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1876  100  1876    0     0   6724      0 --:--:-- --:--:-- --:--:--  6724
Latest is zephyr-v2.3.0-437-gb5764f9902
Checking results/zephyr-v2.3.0-397-g540ed95786/disco_l475_iot1.xml
Page not found.
##[error]Process completed with exit code 1.
```

**Comment by nashif** [comment]
> @nashif Not sure what is the problem here:

will take a look...

**Pull request merged**
