### PR TITLE
v2.7.99-2628-g38ce8d615d4b: stm32 results

### PR DESCRIPTION
**Pull request by erwango**
Non reg result analysis on last run:

Failed tests:
   (verdicts: T/p: Passed, F/f: Failed, t:timeout)
   samples/drivers/lora/receive/sample.driver.lora.receive, nucleo_wl55jc
   samples/drivers/lora/send/sample.driver.lora.send, nucleo_wl55jc
   samples/kernel/metairq_dispatch/sample.kernel.metairq_dispatch, nucleo_f091rc
   samples/kernel/metairq_dispatch/sample.kernel.metairq_dispatch, nucleo_l073rz
   samples/subsys/lorawan/class_a/samples.lorawan.class_a, nucleo_wl55jc
   samples/subsys/nvs/sample.nvs.basic, disco_l475_iot1
   tests/crypto/rand32/crypto.rand32.random_hw_xoshiro, nucleo_wl55jc (instable: ppptpptpppppppt)
   tests/drivers/flash/drivers.flash.stm32, nucleo_h743zi
   tests/drivers/gpio/gpio_api_1pin/peripheral.gpio.1pin, nucleo_wl55jc
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_f429zi
   tests/drivers/uart/uart_async_api/drivers.uart.uart_async_api, nucleo_f746zg
   tests/kernel/common/kernel.common.nano32, nucleo_f746zg (Regression)
   tests/kernel/common/kernel.common.tls, nucleo_h743zi
   tests/kernel/fatal/exception/kernel.common.stack_protection_arm_fpu_sharing, nucleo_f746zg (instable: ppppppppppptppppppptttppppppppppppppp)
   tests/lib/cmsis_dsp/complexmath/libraries.cmsis_dsp.complexmath, nucleo_wb55rg (instable: ppppptpppppppppppppppppppppppppppptpp)
   tests/lib/cmsis_dsp/complexmath/libraries.cmsis_dsp.complexmath.fpu, nucleo_wb55rg (instable: ptppptppppppppppppppppppppppppptppppp)
   tests/lib/cmsis_dsp/filtering/libraries.cmsis_dsp.filtering.misc, stm32l562e_dk (instable: ppppppppptttppppppppppppttppppppppppp)
   tests/lib/cmsis_dsp/filtering/libraries.cmsis_dsp.filtering.misc.fpu, nucleo_h743zi
   tests/lib/cmsis_dsp/statistics/libraries.cmsis_dsp.statistics, stm32l562e_dk (instable: pppppppppppppppppppppppppppppppptptpp)
   tests/lib/cmsis_dsp/statistics/libraries.cmsis_dsp.statistics.fpu, nucleo_wb55rg (instable: ppptpttpppppppppppppppppppppppppppppp)
   tests/lib/cmsis_dsp/statistics/libraries.cmsis_dsp.statistics.fpu, stm32l562e_dk (Regression)
   tests/lib/cmsis_dsp/support/libraries.cmsis_dsp.support.fpu, nucleo_f429zi (instable: pppppppppppptttptpppppptpppptpppppppp)
   tests/lib/p4workq/lib.p4wq, disco_l475_iot1 (instable: ppptttttttpptpppppppppppttppppppppppp)
   tests/lib/p4workq/lib.p4wq, stm32l562e_dk
   tests/subsys/canbus/isotp/implementation/can.isotp.implemmentation, nucleo_g474re
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, disco_l475_iot1 (instable: pppptppppptppttpppptppppppppppptppptp)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, nucleo_f429zi (instable: pptttptpppptpppppppptpppppppppppppppt)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, nucleo_wb55rg (instable: pptpptpptpptpppptpppppppppppppppppppp)
   tests/subsys/logging/log_immediate/logging.log_immediate.clean_output, stm32l562e_dk (instable: ptpppppptppppppppppppppppppppptpppppp)

Total: 29 test(s) failed out of 4558 tests run
       4529 test(s) passed
       2 regression(s) on stable test
Recently skipped: 15

Signed-off-by: Erwan Gouriou <erwan.gouriou@linaro.org>

### CODE REVIEW

**Review by hakehuang — APPROVED** [review]

**Comment by hakehuang** [comment]
@erwango Size of the XML report at results/v2.7.99-2628-g38ce8d615d4b/nucleo_h743zi.xml is >5.0 Mb can you remove logs in this file? if you have reported issues already?

**Comment by erwango** [comment]
> @erwango Size of the XML report at results/v2.7.99-2628-g38ce8d615d4b/nucleo_h743zi.xml is >5.0 Mb can you remove logs in this file? if you have reported issues already?

@hakehuang I would be able to do it for this specific file, but I can't afford to perform this operation systematically.
So either we should work on providing shorter files either we should increase the 5Mb limit.
For instance, do you know if the logs are provided in the file for each test result or is it provided only for failed test ?

**Comment by hakehuang** [comment]
> or instance, do you know if the logs are provided in the file for each test result or is it provided only for failed test ?

it will only for failure cases, but looks like in you case the failure log is too long. @PerMac @nashif do you have any idea on how to handle such issue?

**Comment by PerMac** [comment]
I've increased the max size to 10 Mb. However, I think we still have to thin down the reports. 5Mb+ is quite big

**Comment by hakehuang** [comment]
maybe we need think about a compress post process, if the log is too large.

**Pull request closed without merging**
